"""add composite index user_role on quiz_ownership

Revision ID: 19a36dc8705a
Revises: 30e8ff7978c5
Create Date: 2026-01-15 17:33:30.076411

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "19a36dc8705a"
down_revision: Union[str, Sequence[str], None] = "30e8ff7978c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_quiz_ownership_user_role",
        "quiz_ownership",
        ["user_id", "role"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_quiz_ownership_user_role", table_name="quiz_ownership")
    # ### end Alembic commands ###
