"""Add Quiz module tables

Revision ID: 30e8ff7978c5
Revises: c33e11a76423
Create Date: 2026-01-15 11:45:47.921523

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "30e8ff7978c5"
down_revision: Union[str, Sequence[str], None] = "c33e11a76423"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quiz",
        sa.Column("quiz_id", sa.Uuid(), nullable=False, comment="UUID primary key"),
        sa.Column("title", sa.String(length=255), nullable=False, comment="Quiz title"),
        sa.Column(
            "topic",
            sa.String(length=255),
            nullable=False,
            comment="Main topic/subject of the quiz",
        ),
        sa.Column(
            "state",
            sa.Enum(
                "PRIVATE",
                "PROTECTED",
                "PUBLIC",
                name="quizstate",
                native_enum=False,
                length=20,
            ),
            nullable=False,
            comment="Visibility state (private/protected/public)",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "GENERATING",
                "COMPLETED",
                "FAILED",
                name="quizstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
            comment="Generation status (pending/generating/completed/failed)",
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False, comment="UUID of creator"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when quiz was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when quiz was last updated",
        ),
        sa.PrimaryKeyConstraint("quiz_id"),
    )
    op.create_index(op.f("ix_quiz_created_by"), "quiz", ["created_by"], unique=False)
    op.create_table(
        "quiz_ownership",
        sa.Column(
            "ownership_id",
            sa.Uuid(),
            nullable=False,
            comment="UUID primary key",
        ),
        sa.Column("quiz_id", sa.Uuid(), nullable=False, comment="Foreign key to quiz"),
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
            comment="UUID of user (no FK - cross-module reference to auth.user)",
        ),
        sa.Column(
            "role",
            sa.Enum(
                "OWNER",
                "EDITOR",
                "VIEWER",
                name="ownershiprole",
                native_enum=False,
                length=20,
            ),
            nullable=False,
            comment="Access level (owner/editor/viewer)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when ownership was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when ownership was last updated",
        ),
        sa.ForeignKeyConstraint(["quiz_id"], ["quiz.quiz_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("ownership_id"),
        sa.UniqueConstraint("quiz_id", "user_id", name="uq_quiz_ownership_quiz_user"),
    )
    op.create_index(
        op.f("ix_quiz_ownership_quiz_id"),
        "quiz_ownership",
        ["quiz_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quiz_ownership_user_id"),
        "quiz_ownership",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "task",
        sa.Column("task_id", sa.Uuid(), nullable=False, comment="UUID primary key"),
        sa.Column("quiz_id", sa.Uuid(), nullable=False, comment="Foreign key to quiz"),
        sa.Column(
            "type",
            sa.Enum(
                "MULTIPLE_CHOICE",
                "FREE_TEXT",
                "CLOZE",
                name="tasktype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
            comment="Task type discriminator",
        ),
        sa.Column(
            "prompt",
            sa.Text(),
            nullable=False,
            comment="Question or instruction text",
        ),
        sa.Column(
            "topic_detail",
            sa.String(length=255),
            nullable=False,
            comment="Specific topic or subtopic",
        ),
        sa.Column(
            "order_index",
            sa.Integer(),
            nullable=False,
            comment="Position within quiz (0-indexed)",
        ),
        sa.ForeignKeyConstraint(["quiz_id"], ["quiz.quiz_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_index(
        "ix_task_quiz_order",
        "task",
        ["quiz_id", "order_index"],
        unique=False,
    )
    op.create_table(
        "task_cloze",
        sa.Column(
            "task_id",
            sa.Uuid(),
            nullable=False,
            comment="Foreign key to base task",
        ),
        sa.Column(
            "template_text",
            sa.Text(),
            nullable=False,
            comment="Text with placeholders like {{blank_0}}, {{blank_1}}",
        ),
        sa.ForeignKeyConstraint(["task_id"], ["task.task_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_table(
        "task_free_text",
        sa.Column(
            "task_id",
            sa.Uuid(),
            nullable=False,
            comment="Foreign key to base task",
        ),
        sa.Column(
            "reference_answer",
            sa.Text(),
            nullable=False,
            comment="Model answer for evaluation comparison",
        ),
        sa.ForeignKeyConstraint(["task_id"], ["task.task_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_table(
        "task_multiple_choice",
        sa.Column(
            "task_id",
            sa.Uuid(),
            nullable=False,
            comment="Foreign key to base task",
        ),
        sa.ForeignKeyConstraint(["task_id"], ["task.task_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_table(
        "task_cloze_blank",
        sa.Column("blank_id", sa.Uuid(), nullable=False, comment="UUID primary key"),
        sa.Column(
            "task_id",
            sa.Uuid(),
            nullable=False,
            comment="Foreign key to cloze task",
        ),
        sa.Column(
            "position",
            sa.Integer(),
            nullable=False,
            comment="Position/index of blank in template (0-indexed)",
        ),
        sa.Column(
            "expected_value",
            sa.String(length=255),
            nullable=False,
            comment="Expected answer for this blank",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task_cloze.task_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("blank_id"),
    )
    op.create_index(
        op.f("ix_task_cloze_blank_task_id"),
        "task_cloze_blank",
        ["task_id"],
        unique=False,
    )
    op.create_table(
        "task_multiple_choice_option",
        sa.Column("option_id", sa.Uuid(), nullable=False, comment="UUID primary key"),
        sa.Column(
            "task_id",
            sa.Uuid(),
            nullable=False,
            comment="Foreign key to multiple choice task",
        ),
        sa.Column("text", sa.Text(), nullable=False, comment="Option text"),
        sa.Column(
            "is_correct",
            sa.Boolean(),
            nullable=False,
            comment="Whether this option is correct",
        ),
        sa.Column(
            "explanation",
            sa.Text(),
            nullable=True,
            comment="Optional explanation for this option",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task_multiple_choice.task_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("option_id"),
    )
    op.create_index(
        op.f("ix_task_multiple_choice_option_task_id"),
        "task_multiple_choice_option",
        ["task_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_task_multiple_choice_option_task_id"),
        table_name="task_multiple_choice_option",
    )
    op.drop_table("task_multiple_choice_option")
    op.drop_index(op.f("ix_task_cloze_blank_task_id"), table_name="task_cloze_blank")
    op.drop_table("task_cloze_blank")
    op.drop_table("task_multiple_choice")
    op.drop_table("task_free_text")
    op.drop_table("task_cloze")
    op.drop_index("ix_task_quiz_order", table_name="task")
    op.drop_table("task")
    op.drop_index(op.f("ix_quiz_ownership_user_id"), table_name="quiz_ownership")
    op.drop_index(op.f("ix_quiz_ownership_quiz_id"), table_name="quiz_ownership")
    op.drop_table("quiz_ownership")
    op.drop_index(op.f("ix_quiz_created_by"), table_name="quiz")
    op.drop_table("quiz")
    # ### end Alembic commands ###
