"""feat(learning): add attempt and answer tables

Revision ID: 3f21ababfc70
Revises: 19a36dc8705a
Create Date: 2026-01-16 19:16:39.777842

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3f21ababfc70"
down_revision: Union[str, Sequence[str], None] = "19a36dc8705a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attempt",
        sa.Column("attempt_id", sa.Uuid(), nullable=False, comment="UUID primary key"),
        sa.Column(
            "quiz_id",
            sa.Uuid(),
            nullable=False,
            comment="UUID reference to quiz",
        ),
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
            comment="UUID reference to user",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "IN_PROGRESS",
                "EVALUATED",
                name="attemptstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
            comment="Attempt status (in_progress/evaluated)",
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when attempt was started",
        ),
        sa.Column(
            "evaluated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when attempt was evaluated",
        ),
        sa.Column(
            "total_percentage",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
            comment="Overall score as percentage (0-100)",
        ),
        sa.PrimaryKeyConstraint("attempt_id"),
    )
    op.create_index("ix_attempt_quiz_id", "attempt", ["quiz_id"], unique=False)
    op.create_index("ix_attempt_status", "attempt", ["status"], unique=False)
    op.create_index("ix_attempt_user_id", "attempt", ["user_id"], unique=False)
    op.create_table(
        "answer",
        sa.Column("answer_id", sa.Uuid(), nullable=False, comment="UUID primary key"),
        sa.Column(
            "attempt_id",
            sa.Uuid(),
            nullable=False,
            comment="Foreign key to attempt",
        ),
        sa.Column(
            "task_id",
            sa.Uuid(),
            nullable=False,
            comment="UUID reference to task",
        ),
        sa.Column(
            "type",
            sa.Enum(
                "MULTIPLE_CHOICE",
                "FREE_TEXT",
                "CLOZE",
                name="answertype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
            comment="Answer type discriminator",
        ),
        sa.Column(
            "percentage_correct",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
            comment="Score as percentage (0-100)",
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attempt.attempt_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("answer_id"),
        sa.UniqueConstraint("attempt_id", "task_id", name="uq_answer_attempt_task"),
    )
    op.create_index("ix_answer_attempt_id", "answer", ["attempt_id"], unique=False)
    op.create_index("ix_answer_task_id", "answer", ["task_id"], unique=False)
    op.create_table(
        "answer_cloze",
        sa.Column(
            "answer_id",
            sa.Uuid(),
            nullable=False,
            comment="Foreign key to base answer",
        ),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["answer.answer_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("answer_id"),
    )
    op.create_table(
        "answer_free_text",
        sa.Column(
            "answer_id",
            sa.Uuid(),
            nullable=False,
            comment="Foreign key to base answer",
        ),
        sa.Column(
            "text_response",
            sa.Text(),
            nullable=False,
            comment="User's written answer text",
        ),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["answer.answer_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("answer_id"),
    )
    op.create_table(
        "answer_multiple_choice",
        sa.Column(
            "answer_id",
            sa.Uuid(),
            nullable=False,
            comment="Foreign key to base answer",
        ),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["answer.answer_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("answer_id"),
    )
    op.create_table(
        "answer_cloze_item",
        sa.Column(
            "answer_id",
            sa.Uuid(),
            nullable=False,
            comment="Foreign key to cloze answer",
        ),
        sa.Column(
            "blank_id",
            sa.Uuid(),
            nullable=False,
            comment="UUID reference to task blank",
        ),
        sa.Column(
            "provided_value",
            sa.Text(),
            nullable=False,
            comment="User's provided text for this blank",
        ),
        sa.Column(
            "is_correct",
            sa.Boolean(),
            nullable=True,
            comment="Whether the provided value is correct",
        ),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["answer_cloze.answer_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("answer_id", "blank_id"),
    )
    op.create_table(
        "answer_multiple_choice_selection",
        sa.Column(
            "answer_id",
            sa.Uuid(),
            nullable=False,
            comment="Foreign key to multiple choice answer",
        ),
        sa.Column(
            "option_id",
            sa.Uuid(),
            nullable=False,
            comment="UUID reference to task option",
        ),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["answer_multiple_choice.answer_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("answer_id", "option_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("answer_multiple_choice_selection")
    op.drop_table("answer_cloze_item")
    op.drop_table("answer_multiple_choice")
    op.drop_table("answer_free_text")
    op.drop_table("answer_cloze")
    op.drop_index("ix_answer_task_id", table_name="answer")
    op.drop_index("ix_answer_attempt_id", table_name="answer")
    op.drop_table("answer")
    op.drop_index("ix_attempt_user_id", table_name="attempt")
    op.drop_index("ix_attempt_status", table_name="attempt")
    op.drop_index("ix_attempt_quiz_id", table_name="attempt")
    op.drop_table("attempt")
    # ### end Alembic commands ###
