"""add quiz share links

Revision ID: 46599c599156
Revises: 3f21ababfc70
Create Date: 2026-01-29 14:54:07.835473

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "46599c599156"
down_revision: Union[str, Sequence[str], None] = "3f21ababfc70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quiz_share_link",
        sa.Column(
            "share_link_id",
            sa.Uuid(),
            nullable=False,
            comment="UUID primary key",
        ),
        sa.Column(
            "quiz_id",
            sa.Uuid(),
            nullable=False,
            comment="UUID of the quiz being shared",
        ),
        sa.Column(
            "token",
            sa.String(length=255),
            nullable=False,
            comment="Unique cryptographic token for the share link",
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False, comment="UUID of creator"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when link was created",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Optional expiration timestamp (null = never expires)",
        ),
        sa.Column(
            "max_uses",
            sa.Integer(),
            nullable=True,
            comment="Optional maximum number of uses (null = unlimited)",
        ),
        sa.Column(
            "current_uses",
            sa.Integer(),
            nullable=False,
            comment="Current number of times the link has been used",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether link is active (can be revoked)",
        ),
        sa.ForeignKeyConstraint(["quiz_id"], ["quiz.quiz_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("share_link_id"),
    )
    op.create_index(
        op.f("ix_quiz_share_link_created_by"),
        "quiz_share_link",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quiz_share_link_quiz_id"),
        "quiz_share_link",
        ["quiz_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quiz_share_link_token"),
        "quiz_share_link",
        ["token"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quiz_share_link_token"), table_name="quiz_share_link")
    op.drop_index(op.f("ix_quiz_share_link_quiz_id"), table_name="quiz_share_link")
    op.drop_index(op.f("ix_quiz_share_link_created_by"), table_name="quiz_share_link")
    op.drop_table("quiz_share_link")
    # ### end Alembic commands ###
