"""Add magic_link_token table

Revision ID: c33e11a76423
Revises: d2bf9d1c6cf0
Create Date: 2025-12-11 15:30:09.249620

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c33e11a76423"
down_revision: Union[str, Sequence[str], None] = "d2bf9d1c6cf0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "magic_link_token",
        sa.Column("id", sa.Uuid(), nullable=False, comment="UUID primary key"),
        sa.Column(
            "token_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 hash of the magic link token",
        ),
        sa.Column(
            "email_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 hash of the user's email address",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when the token was created",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when the token expires",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_magic_link_token_email_hash"),
        "magic_link_token",
        ["email_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_magic_link_token_expires_at"),
        "magic_link_token",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_magic_link_token_token_hash"),
        "magic_link_token",
        ["token_hash"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_magic_link_token_token_hash"), table_name="magic_link_token")
    op.drop_index(op.f("ix_magic_link_token_expires_at"), table_name="magic_link_token")
    op.drop_index(op.f("ix_magic_link_token_email_hash"), table_name="magic_link_token")
    op.drop_table("magic_link_token")
    # ### end Alembic commands ###
