"""Add user table

Revision ID: d2bf9d1c6cf0
Revises:
Create Date: 2025-12-05 18:37:18.745732

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d2bf9d1c6cf0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
            comment="UUID primary key and reference point for all data relationships",
        ),
        sa.Column(
            "email_hash",
            sa.String(length=64),
            nullable=False,
            comment="Hash of email address for Magic Link assignment",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when the user account was created",
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_user_email_hash"), "user", ["email_hash"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email_hash"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
